from . permutations import InterestingPermutations

class Peals(InterestingPermutations):
    """Use permutations to make peals and represent peals as permutations.
    
    http://www.gutenberg.org/files/18567/18567-h/18567-h.htm"""
    def __init__(self):
        InterestingPermutations.__init__(self)
        self.peals={}
        self.makeRotateHalfs() # original and the rotation r that r*r=e. Alternate r1*r2=e if nelements==odd
        self.makeMirror() # original and miror
        self.makeFullRotations() # original and each rotation clockwise (0->n-1)
        self.makeFullMirrors() # sequences to fit overall sizes or not..
        self.makeOtherFullCycles() # generated by permutations with all elements while not a rotation or a mirror. # non-topological?
        self.canonicalPeal() # with the hunts, etc. 
        self.transpositionsPeal(self.peals["rotation_peal"][1])
        self.TwentyAllOver() # 
        self.anEightAndForty() # 
    def canonicalPeal(self,hunts=None):
        domain=list(range(self.nelements))
        if hunts==None:
            hunts={}
            if len(self.nelements)<5:
                hunts=dict(level=1,index=0,status="started",starting_direction="up")
            else:
                hunts=dict(level=1,index=0,starting_direction="up",level=2,index=1,starting_direction="up")
        neighbor_swaps=[sympy.combinatorics.Permutation(i,i+1) for i in range(self.nelements-1)]
        peal=[self.applyStep(domain,hunts)]
        while peal[-1]!=domain:
            sequence,hunts=self.applyStep(peal[-1],hunts)
            peal+=[sequence]
    def moveDomain(self,domain,sequence):
    def act(self,peal="rotation",domain=None):
        if domain==None:
            domain=list(range(self.nelements))
        return [i(domain) for i in self.peals[peal]]
    def actAll(self,domain=None):
        if domain==None:
            domain=list(range(self.nelements))
        acted_peals={}
        for peal in self.peals:
            acted_peals[peal+"_acted"]=[i(domain) for i in self.peals[peal]]
        self.domain=domain
        self.acted_peals=acted_peals
    def transpositionsPeal(permutation,peal_name="transposition_peal"):
        self.peals[peal_name]=[sympy.combinatorics.Permutation(i) for i in permutation.transpositions()]


